
version: "3"
services:

  builder:
    build:
      context: ./
      dockerfile: ./image.docker
      # args:
        # - "HTTP_PROXY=http://gateway.zscaler.net:9480"
        # - "HTTPS_PROXY=http://gateway.zscaler.net:9480"
        # - "NO_PROXY=127.0.0.1,192.168.99.100,10.229.206.135,swtfsiws,dev.wonderware.com"
    image: "rogersantos/builder:windows_x86"
    stdin_open: true
    tty: true
