version: '3'
services:
  reverse_proxy_server:
    image: 'nginx'
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8083:80
  # package_server:
  #   image: 'rogersantos/conan_repository_server'
  #   volumes:
  #     - package_server_data:/var/opt/jfrog/artifactory
  #   ports:
  #     - 8082:8081
  # package_client:
  #   image: 'rogersantos/conan_linux_x64_gcc6'
  #   command: tail -f /dev/null
  #   depends_on:
  #     - package_server
volumes:
  package_server_data:
