

version: "3"


services:

  # Desktop: http://localhost:10000/index.html?encoding=rgb32
  # Options: http://localhost:10000/connect.html
  x11-bridge:
    # build:
    #   context: ./
    #   dockerfile: ./image.docker
    image: "jare/x11-bridge"
    stdin_open: true
    tty: true
    environment: 
      - MODE=tcp
      - XPRA_HTML=yes
      - DISPLAY=:14 
    volumes:
      - x11-bridge-pub-keys:/etc/pub-keys
      - x11-bridge-X11-unix:/tmp/.X11-unix
    ports:
      - 10000:10000 

  emacs-1:
    image: "jare/emacs"
    stdin_open: true
    tty: true
    environment: 
      - DISPLAY=:14 
    volumes:
      - x11-bridge-pub-keys:/etc/pub-keys
      - x11-bridge-X11-unix:/tmp/.X11-unix
    command: ["emacs"]
    depends_on:
      - x11-bridge

  emacs-2:
    image: "jare/emacs"
    stdin_open: true
    tty: true
    environment: 
      - DISPLAY=:14 
    volumes:
      - x11-bridge-pub-keys:/etc/pub-keys
      - x11-bridge-X11-unix:/tmp/.X11-unix
    command: ["emacs"]
    depends_on:
      - x11-bridge

volumes:
  x11-bridge-pub-keys:
  x11-bridge-X11-unix:
