# Commands
# docker-compose.exe up -d
# docker-compose stop
# docker-compose.exe down (Remove)

version: "3"
services:

  # os_stage:
  #   build:
  #     context: ./
  #     dockerfile: ./stage.docker
  #   image: "windows_core_debugger_stage:windows"
  #   entrypoint: "powershell"
  #   stdin_open: true
  #   tty: true

  windows_core_debugger:
    build:
      context: ./
      dockerfile: ./windows_core_debugger.docker
    image: "rogersantos/windows_core_debugger:windows"
    entrypoint: "powershell"
    stdin_open: true
    tty: true
